version: '3.8'

services:
  app:
    image: node:14
    container_name: node-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
